config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  resources :members

  resources :books

end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :book
  belongs_to :member
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: [:show, :edit, :update, :destroy]

  # GET /borrows
  # GET /borrows.json
  def index
    @borrows = Borrow.all
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
  end

  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows
  # POST /borrows.json
  def create
    @borrow = Borrow.new(borrow_params)

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to @borrow, notice: 'Borrow was successfully created.' }
        format.json { render :show, status: :created, location: @borrow }
      else
        format.html { render :new }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrows/1
  # PATCH/PUT /borrows/1.json
  def update
    respond_to do |format|
      if @borrow.update(borrow_params)
        format.html { redirect_to @borrow, notice: 'Borrow was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrow }
      else
        format.html { render :edit }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow.destroy
    respond_to do |format|
      format.html { redirect_to borrows_url, notice: 'Borrow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrow_params
      params.require(:borrow).permit(:idate, :rdate, :book_id, :member_id)
    end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/views/borrows/_form.html.erb
<%= form_for(@borrow) do |f| %>
  <% if @borrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
      <% @borrow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idate %><br>
    <%= f.date_select :idate %>
  </div>
  <div class="field">
    <%= f.label :rdate %><br>
    <%= f.date_select :rdate %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrows/edit.html.erb
<h1>Editing Borrow</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrow %> |
<%= link_to 'Back', borrows_path %>

app/views/borrows/index.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color: 	#7FFFD4">
<center> <style="font-size:300%">
<h1>Welcome In Library Managment system </h1>
<h2><b><strong><u><style="font-size:300%">Listing Borrow</u></b></strong></h2>

<table border="10" bordercolor="red" <table style="width:80%"><style="font-size:500%">
<tr><tr><style="font-size:300%">

  <thead>
    <tr>
      <th><b>Idate</b></th>
      <th><b>Rdate</b></th>
      <th><b>Book id</b></th>
      <th><b>Member id</b></th>
       <th><b>Book tilte</b></th>
       <th><b>Member name</b></th>
       
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrows.each do |borrow| %>
      <tr>
        <td><%= borrow.idate %></td>
        <td><%= borrow.rdate %></td>
        <td><%= borrow.book_id %></td>
        <td><%= borrow.member_id %></td>
        <td><%= borrow.book.tilte %></td>
        <td><%= borrow.member.name %></td>


        <td><%= link_to 'Show', borrow %></td>
        <td><%= link_to 'Edit', edit_borrow_path(borrow)%> </td>
        <td><%= link_to 'Destroy', borrow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrow', new_borrow_path %>

app/views/borrows/new.html.erb
<h1>New Borrow</h1>

<%= render 'form' %>

<%= link_to 'Back', borrows_path %>

app/views/borrows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idate:</strong>
  <%= @borrow.idate %>
</p>

<p>
  <strong>Rdate:</strong>
  <%= @borrow.rdate %>
</p>

<p>
  <strong>Book:</strong>
  <%= @borrow.book %>
</p>

<p>
  <strong>Member:</strong>
  <%= @borrow.member %>
</p>

<%= link_to 'Edit', edit_borrow_path(@borrow) %> |
<%= link_to 'Back', borrows_path %>